version: "3.5"
services:
  validator-ejector:
    build:
      context: validator-ejector
      args:
        EJECTOR_VERSION: 1.9.0
        STAKER_SCRIPTS_VERSION: v0.1.2
    environment:
      OPERATOR_ID: ""
      CHARON_TO_EXIT_NUMBER: 1
      BLOCKS_PRELOAD: 50000
    restart: on-failure
    volumes:
      - validator-ejector:/exitmessages
  lido-dv-exit:
    build:
      context: lido-dv-exit
      args:
        DV_EXIT_VERSION: v0.3.0
        STAKER_SCRIPTS_VERSION: v0.1.2
    environment:
      LOG_LEVEL: info
      VALIDATOR_QUERY_CHUNK_SIZE: 5
      CHARON_TO_EXIT_NUMBER: 1
      EXIT_EPOCH: 194048
    restart: on-failure
    volumes:
      - validator-ejector:/exitmessages
      - charon-data:/charon
volumes:
  validator-ejector: {}
  charon-data: {}
